name: Unit Tests
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
        id: go
      - uses: actions/checkout@v4
      - name: Build
        run: |
          go get -d -v
          go build -v .
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v5
        with:
          go-version: 1.13
        id: go
      - uses: actions/checkout@v4
      - name: Unit Tests
        run: |
          go mod tidy
          make test
